### ISSUE TITLE
[FEAT] 인증 방식 3가지로 제공하는 로직 개발

### ISSUE THREAD

**Issue by yeseul106** [SSAFY-Sandbox/sandbox-BE#9]
## 🚀 About Issue 🚀

- 클라이언트에서 인증 방식을 3가지로 함에 따라 해당 로직을 구현합니다.

## ✅ Todo

- [ ] ATK - 헤더 & RTK - 쿠키
- [ ] ATK - 헤더 & RTK - 헤더
- [ ] ATK - 쿠키 & RTK - 쿠키
